[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@uniswap/contracts=lib/v2-periphery/contracts",
    "@devops=lib/foundry-devops/src",
]
optimizer = true
optimezer_runs = 1000
<<<<<<< HEAD
=======
# match_path = "test/unit/*"
>>>>>>> dd81a9a1b1d5c6e876efecc1801ee01b7f2a1028
# via_ir = true
# ffi = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

<<<<<<< HEAD
=======
[invariant]
runs = 500
depth = 200
fail_on_revert = false


>>>>>>> dd81a9a1b1d5c6e876efecc1801ee01b7f2a1028
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
